# Source: authentik/charts/redis/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: authentik-redis
  namespace: "authentik-dev"
  labels:
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 7.2.3
    helm.sh/chart: redis-18.6.1
---
# Source: authentik/charts/serviceAccount/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik
  namespace: "authentik-dev"
  labels:
    helm.sh/chart: "serviceAccount-2.0.0"
    app.kubernetes.io/name: "serviceAccount"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "authentik"
    app.kubernetes.io/version: "2.0.0"