---
# Source: authentik/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgresql
  namespace: authentik-dev
  annotations:
    avp.kubernetes.io/path: "argocd/data/argocd-vault-plugin/postgresql"
  labels:
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 15.4.0
    helm.sh/chart: postgresql-12.12.10
type: Opaque
stringData:
  password: <authentik_psql_password>
  postgres-password: <authentik_psql_password>
  AUTHENTIK_POSTGRESQL__HOST: <authentik_psql_host>
  AUTHENTIK_POSTGRESQL__NAME: <authentik_psql_name>
  AUTHENTIK_POSTGRESQL__PORT: <authentik_psql_port>
  AUTHENTIK_POSTGRESQL__USER: <authentik_psql_user>
  AUTHENTIK_POSTGRESQL__PASSWORD: <authentik_psql_password>
---
# Source: authentik/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authentik-smtp
  namespace: authentik-dev
  labels:
    helm.sh/chart: "authentik-2024.4.2"
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "authentik"
    app.kubernetes.io/version: "2024.4.2"
  annotations:
    avp.kubernetes.io/path: "argocd/data/argocd-vault-plugin/smtp"    
stringData:  
  AUTHENTIK_EMAIL__FROM: <authentik_email_from>
  AUTHENTIK_EMAIL__HOST: <authentik_email_host>
  AUTHENTIK_EMAIL__PASSWORD: <authentik_email_password>
  AUTHENTIK_EMAIL__PORT: <authentik_email_port>
  AUTHENTIK_EMAIL__TIMEOUT: <authentik_email_timeout>
  AUTHENTIK_EMAIL__USE_SSL: <authentik_email_ssl>
  AUTHENTIK_EMAIL__USE_TLS: <authentik_email_tls>
  AUTHENTIK_EMAIL__USERNAME: <authentik_email_username>

---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-data
  namespace: authentik-dev  
type: Opaque
stringData:
  AUTHENTIK_ERROR_REPORTING__ENABLED: <path:argocd/data/argocd-vault-plugin/authentik#authentik_error_reporting>
  AUTHENTIK_ERROR_REPORTING__ENVIRONMENT: <path:argocd/data/argocd-vault-plugin/authentik#authentik_error_env>
  AUTHENTIK_ERROR_REPORTING__SEND_PII: <path:argocd/data/argocd-vault-plugin/authentik#authentik_error_pii>
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__ASN: <path:argocd/data/argocd-vault-plugin/authentik#authentik_events_asn>
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__GEOIP: <path:argocd/data/argocd-vault-plugin/authentik#authentik_events_geoip>
  AUTHENTIK_LOG_LEVEL: <path:argocd/data/argocd-vault-plugin/authentik#authentik_log_level>
  AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE: <path:argocd/data/argocd-vault-plugin/authentik#authentik_base_image>
  AUTHENTIK_SECRET_KEY: <path:argocd/data/argocd-vault-plugin/authentik#authentik_secret_key>

---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-redis
  namespace: authentik-dev  
type: Opaque
data:
  # AUTHENTIK_REDIS__PASSWORD: <path:argocd/data/argocd-vault-plugin/redis#authentik_redis_password>
  AUTHENTIK_REDIS__HOST: "YXV0aGVudGlrLXJlZGlzLW1hc3Rlcg=="
  # redis-password: <path:argocd/data/argocd-vault-plugin/redis#authentik_redis_password>

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: authentik-dev  
type: Opaque
stringData:
  api-token: <path:argocd/data/argocd-vault-plugin/cloudflare#api-token> # Updated
  email:  <path:argocd/data/argocd-vault-plugin/cloudflare#email> 