# Source: authentik/templates/server/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-server
  namespace: "authentik-dev"
  labels:
    helm.sh/chart: "authentik-2024.4.2"
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/component: "server"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "authentik"
    app.kubernetes.io/version: "2024.4.2"
  annotations:
    cert-manager.io/issuer: authentik-letsencrypt-dev
spec:
  ingressClassName: nginx
  rules:
  - host: authentik-dev.diagon.cloud
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: authentik-server
              port:
                number: 9443
  tls:
  - hosts:
    - authentik-dev.diagon.cloud
    secretName: authentik-tls
