---
# Source: authentik/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authentik-postgresql
  namespace: authentik-dev
  annotations:
    avp.kubernetes.io/path: "argocd/data/argocd-vault-plugin/postgresql"
    # avp.kubernetes.io/path: "argocd/argocd-vault-plugin/authentik"
    # avp.kubernetes.io/path: "argocd/argocd-vault-plugin/redis"
    # avp.kubernetes.io/path: "argocd/argocd-vault-plugin/smtp"
  labels:
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 15.4.0
    helm.sh/chart: postgresql-12.12.10
type: Opaque
data:
  postgres-password: <authentik_psql_root_password> #"RmpOWWJXUjRBSQ=="
  password: <authentik_psql_password> #"enp0WXVYek1NRw=="
  AUTHENTIK_POSTGRESQL__HOST: <authentik_psql_host> #YXV0aGVudGlrLXBvc3RncmVzcWw=
  AUTHENTIK_POSTGRESQL__NAME: <authentik_psql_name> #YXV0aGVudGlr
  AUTHENTIK_POSTGRESQL__PORT: <authentik_psql_port> #NTQzMg==
  AUTHENTIK_POSTGRESQL__USER: <authentik_psql_user> #YXV0aGVudGlr
  AUTHENTIK_POSTGRESQL__PASSWORD: <authentik_psql_password> #YXV0aGVudGlr  
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
---
# Source: authentik/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authentik-smtp
  namespace: authentik-dev
  labels:
    helm.sh/chart: "authentik-2024.4.2"
    app.kubernetes.io/name: "authentik"
    app.kubernetes.io/instance: "authentik"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/part-of: "authentik"
    app.kubernetes.io/version: "2024.4.2"
  annotations:
  #   avp.kubernetes.io/path: "argocd/argocd-vault-plugin/postgresql"
  #   avp.kubernetes.io/path: "argocd/argocd-vault-plugin/authentik"
  #   avp.kubernetes.io/path: "argocd/argocd-vault-plugin/redis"
    avp.kubernetes.io/path: "argocd/data/argocd-vault-plugin/smtp"    
data:  
  AUTHENTIK_EMAIL__FROM: <authentik_email_from>
  AUTHENTIK_EMAIL__HOST: <authentik_email_host>
  AUTHENTIK_EMAIL__PASSWORD: <authentik_email_password>
  AUTHENTIK_EMAIL__PORT: <authentik_email_port> #NTg3
  AUTHENTIK_EMAIL__TIMEOUT: <authentik_email_timeout> #MzA=
  AUTHENTIK_EMAIL__USE_SSL: <authentik_email_ssl> #ZmFsc2U=
  AUTHENTIK_EMAIL__USE_TLS: <authentik_email_tls> #dHJ1ZQ==
  AUTHENTIK_EMAIL__USERNAME: <authentik_email_username>

---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-data
  namespace: authentik-dev  
  # annotations:
  #   avp.kubernetes.io/path: "argocd/argocd-vault-plugin/authentik"
type: Opaque
data:
  AUTHENTIK_ERROR_REPORTING__ENABLED: <path:argocd/data/argocd-vault-plugin/authentik#authentik_error_reporting> #dHJ1ZQ==
  AUTHENTIK_ERROR_REPORTING__ENVIRONMENT: <path:argocd/data/argocd-vault-plugin/authentik#authentik_error_env> #azhz
  AUTHENTIK_ERROR_REPORTING__SEND_PII: <path:argocd/data/argocd-vault-plugin/authentik#authentik_error_pii> #ZmFsc2U=
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__ASN: <path:argocd/data/argocd-vault-plugin/authentik#authentik_events_asn> #L2dlb2lwL0dlb0xpdGUyLUFTTi5tbWRi
  AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__GEOIP: <path:argocd/data/argocd-vault-plugin/authentik#authentik_events_geoip> #L2dlb2lwL0dlb0xpdGUyLUNpdHkubW1kYg==
  AUTHENTIK_LOG_LEVEL: <path:argocd/data/argocd-vault-plugin/authentik#authentik_log_level> #aW5mbw==
  AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE: <path:argocd/data/argocd-vault-plugin/authentik#authentik_base_image>

---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-redis
  namespace: authentik-dev  
type: Opaque
data:
  AUTHENTIK_REDIS__HOST: <path:argocd/data/argocd-vault-plugin/redis#authentik_redis_host> #YXV0aGVudGlrLXJlZGlzLW1hc3Rlcg==


---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: authentik-dev  
type: Opaque
data:
  password: <path:argocd/data/argocd-vault-plugin/#api-token>  